# Based on https://github.com/executablebooks/github-action-demo
name: build

on:
  # TODO build also on PRs
  push:
    branches: [main]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install msprime --pre # Needed until we have a stable 1.0
        pip install -r requirements.txt
    # Build the book
    - name: Build the book
      run: |
        # Would like to run in nitpicky warn mode here, but we lose the
        # ability debug because the log files don't get saved. Doesn't
        # seem to be any way to output the error directly in jupyterbook.
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
